import { TEST_MODEL } from "@dagda/shared/src/entities/_data";
import { EntitiesModel } from "@dagda/shared/src/entities/model";
import { JSTypes } from "@dagda/shared/src/entities/tools/javascript.types";
import { afterEach, beforeEach, describe, expect, inject, it } from "vitest";
import { USERS_TABLE } from "../auth/users";
import { createTestDatabase, TestDatabase } from "../test/pg.fixture";
import { FRAMEWORK_MIGRATIONS } from "./framework.migrations";
import { applyMigrations } from "./migrations";
import { getCreateTableStatement, getFieldSqlType, getTableCreationOrder, qi } from "./schema";

const available = inject("databaseAvailable");

/**
 * A tiny model of its own, kept apart from TEST_MODEL: TEST_MODEL is shared
 * with suites that create its tables without the framework migrations (its
 * "posts" -> "users" foreign key never needs system_users to exist), and a
 * referencesUsers column would make those fail on a missing relation.
 */
const REFERENCES_USERS_MODEL = new EntitiesModel({
    "ID": { rawType: JSTypes.number },
    "TEXT": { rawType: JSTypes.string }
}, {
    "notes": {
        id: { type: "ID", identity: true },
        authorId: { type: "ID", referencesUsers: true, optional: true },
        body: { type: "TEXT" }
    }
});

describe("qi", () => {

    it("quotes an identifier", () => {
        expect(qi("data_posts")).toBe(`"data_posts"`);
    });

    it("escapes an embedded quote rather than letting it break out", () => {
        expect(qi(`ev"il`)).toBe(`"ev""il"`);
    });

});

describe("getFieldSqlType", () => {

    it("makes the identity generated by the database", () => {
        expect(getFieldSqlType(TEST_MODEL, "users", "id")).toBe("SERIAL");
    });

    it("stores a foreign key as what SERIAL produces", () => {
        // Not DOUBLE PRECISION, which is what the raw number type would give:
        // it has to match the referenced identity or the constraint is refused.
        expect(getFieldSqlType(TEST_MODEL, "posts", "author")).toBe("INTEGER");
    });

    it("maps the base types", () => {
        expect(getFieldSqlType(TEST_MODEL, "users", "name")).toBe("TEXT");
        expect(getFieldSqlType(TEST_MODEL, "posts", "pinned")).toBe("BOOLEAN");
    });

    it("maps a plain number to DOUBLE PRECISION", () => {
        // A JS number *is* a double, so this is the only mapping that cannot
        // lose a value the application is able to hold.
        expect(getFieldSqlType(TEST_MODEL, "users", "age")).toBe("DOUBLE PRECISION");
    });

    it("maps an enumeration to the type of its values", () => {
        expect(getFieldSqlType(TEST_MODEL, "posts", "status")).toBe("INTEGER");
        expect(getFieldSqlType(TEST_MODEL, "posts", "kind")).toBe("TEXT");
    });

    it("names the table and the field when the type is undeclared", () => {
        expect(() => getFieldSqlType(TEST_MODEL, "posts", "nonExistent"))
            .toThrow(/posts.*nonExistent/);
    });

});

describe("getCreateTableStatement", () => {

    it("declares the identity as the primary key", () => {
        const sql = getCreateTableStatement(TEST_MODEL, "users");
        expect(sql).toContain(`"id" SERIAL PRIMARY KEY`);
    });

    it("prefixes the table with data_", () => {
        expect(getCreateTableStatement(TEST_MODEL, "users")).toContain(`CREATE TABLE "data_users"`);
    });

    it("marks the mandatory fields NOT NULL and leaves the optional ones alone", () => {
        const sql = getCreateTableStatement(TEST_MODEL, "users");
        expect(sql).toContain(`"name" TEXT NOT NULL`);
        expect(sql).toMatch(/"age" DOUBLE PRECISION(?! NOT NULL)/);
    });

    it("points a foreign key at the prefixed table", () => {
        expect(getCreateTableStatement(TEST_MODEL, "posts"))
            .toContain(`"author" INTEGER NOT NULL REFERENCES "data_users"("id")`);
    });

    it("can be made idempotent", () => {
        expect(getCreateTableStatement(TEST_MODEL, "users", { ifNotExists: true }))
            .toContain(`CREATE TABLE IF NOT EXISTS`);
    });

    it("leaves out the fields removed by a version", () => {
        // `size` carries toVersion, so it belongs to the past, not to the schema.
        expect(getCreateTableStatement(TEST_MODEL, "users")).not.toContain(`"size"`);
    });

    it("points a field declared referencesUsers at the framework's accounts table", () => {
        expect(getCreateTableStatement(REFERENCES_USERS_MODEL, "notes"))
            .toContain(`"authorId" INTEGER REFERENCES "system_users"("id") ON DELETE SET NULL`);
    });

});

describe.runIf(available)("getCreateTableStatement, against a real database", () => {

    let db: TestDatabase;

    beforeEach(async () => {
        db = await createTestDatabase("schema-references-users");
        await applyMigrations(db.runner, REFERENCES_USERS_MODEL, FRAMEWORK_MIGRATIONS, "framework");
        await db.runner.run(getCreateTableStatement(REFERENCES_USERS_MODEL, "notes"));
    });

    afterEach(async () => {
        await db?.dispose();
    });

    it("clears the column rather than failing when the referenced account is deleted", async () => {
        const user = await db.runner.get<{ id: number }>(
            `INSERT INTO ${qi(USERS_TABLE)} (${qi("login")}, ${qi("displayName")}, ${qi("password")}, ${qi("isSuperAdmin")})
             VALUES ($1, $2, $3, FALSE) RETURNING ${qi("id")}`,
            "alice", "Alice", "irrelevant"
        );
        const note = await db.runner.get<{ id: number }>(
            `INSERT INTO "data_notes" (${qi("authorId")}, ${qi("body")}) VALUES ($1, $2) RETURNING ${qi("id")}`,
            user!.id, "hello"
        );

        await db.runner.run(`DELETE FROM ${qi(USERS_TABLE)} WHERE ${qi("id")} = $1`, user!.id);

        const row = await db.runner.get<{ authorId: number | null }>(
            `SELECT ${qi("authorId")} FROM "data_notes" WHERE ${qi("id")} = $1`, note!.id
        );
        expect(row?.authorId).toBeNull();
    });

});

describe("getTableCreationOrder", () => {

    it("puts a table after the ones it references", () => {
        const order = getTableCreationOrder(TEST_MODEL);
        expect(order.indexOf("users")).toBeLessThan(order.indexOf("posts"));
    });

    it("returns every table exactly once", () => {
        const order = getTableCreationOrder(TEST_MODEL);
        expect([...order].sort()).toEqual([...TEST_MODEL.getTableNames()].map(String).sort());
    });

});
