import { TEST_MODEL } from "@dagda/shared/src/entities/_data";
import { describe, expect, it } from "vitest";
import { getCreateTableStatement, getFieldSqlType, getTableCreationOrder, qi } from "./schema";

describe("qi", () => {

    it("quotes an identifier", () => {
        expect(qi("data_posts")).toBe(`"data_posts"`);
    });

    it("escapes an embedded quote rather than letting it break out", () => {
        expect(qi(`ev"il`)).toBe(`"ev""il"`);
    });

});

describe("getFieldSqlType", () => {

    it("makes the identity generated by the database", () => {
        expect(getFieldSqlType(TEST_MODEL, "users", "id")).toBe("SERIAL");
    });

    it("stores a foreign key as what SERIAL produces", () => {
        // Not DOUBLE PRECISION, which is what the raw number type would give:
        // it has to match the referenced identity or the constraint is refused.
        expect(getFieldSqlType(TEST_MODEL, "posts", "author")).toBe("INTEGER");
    });

    it("maps the base types", () => {
        expect(getFieldSqlType(TEST_MODEL, "users", "name")).toBe("TEXT");
        expect(getFieldSqlType(TEST_MODEL, "posts", "pinned")).toBe("BOOLEAN");
    });

    it("maps a plain number to DOUBLE PRECISION", () => {
        // A JS number *is* a double, so this is the only mapping that cannot
        // lose a value the application is able to hold.
        expect(getFieldSqlType(TEST_MODEL, "users", "age")).toBe("DOUBLE PRECISION");
    });

    it("maps an enumeration to the type of its values", () => {
        expect(getFieldSqlType(TEST_MODEL, "posts", "status")).toBe("INTEGER");
        expect(getFieldSqlType(TEST_MODEL, "posts", "kind")).toBe("TEXT");
    });

    it("names the table and the field when the type is undeclared", () => {
        expect(() => getFieldSqlType(TEST_MODEL, "posts", "nonExistent"))
            .toThrow(/posts.*nonExistent/);
    });

});

describe("getCreateTableStatement", () => {

    it("declares the identity as the primary key", () => {
        const sql = getCreateTableStatement(TEST_MODEL, "users");
        expect(sql).toContain(`"id" SERIAL PRIMARY KEY`);
    });

    it("prefixes the table with data_", () => {
        expect(getCreateTableStatement(TEST_MODEL, "users")).toContain(`CREATE TABLE "data_users"`);
    });

    it("marks the mandatory fields NOT NULL and leaves the optional ones alone", () => {
        const sql = getCreateTableStatement(TEST_MODEL, "users");
        expect(sql).toContain(`"name" TEXT NOT NULL`);
        expect(sql).toMatch(/"age" DOUBLE PRECISION(?! NOT NULL)/);
    });

    it("points a foreign key at the prefixed table", () => {
        expect(getCreateTableStatement(TEST_MODEL, "posts"))
            .toContain(`"author" INTEGER NOT NULL REFERENCES "data_users"("id")`);
    });

    it("can be made idempotent", () => {
        expect(getCreateTableStatement(TEST_MODEL, "users", { ifNotExists: true }))
            .toContain(`CREATE TABLE IF NOT EXISTS`);
    });

    it("leaves out the fields removed by a version", () => {
        // `size` carries toVersion, so it belongs to the past, not to the schema.
        expect(getCreateTableStatement(TEST_MODEL, "users")).not.toContain(`"size"`);
    });

});

describe("getTableCreationOrder", () => {

    it("puts a table after the ones it references", () => {
        const order = getTableCreationOrder(TEST_MODEL);
        expect(order.indexOf("users")).toBeLessThan(order.indexOf("posts"));
    });

    it("returns every table exactly once", () => {
        const order = getTableCreationOrder(TEST_MODEL);
        expect([...order].sort()).toEqual([...TEST_MODEL.getTableNames()].map(String).sort());
    });

});
