import { EntitiesModel } from "@dagda/shared/src/entities/model";
import { EnumDefinition } from "@dagda/shared/src/entities/tools/enums";
import { JSTypes } from "@dagda/shared/src/entities/tools/javascript.types";
import { USERS_TABLE } from "../auth/users";

/**
 * Derives PostgreSQL DDL from the entities model.
 *
 * This does *not* synchronise a schema: FEATURES §2 rules that out, because a
 * renamed field would read as a drop followed by a create, so a silent data
 * loss. What it does is spare the developer from hand-typing the SQL of a table
 * he has already declared — the statements produced here are meant to be run
 * from a migration, which stays explicit and versioned.
 */

/** Quote an identifier (table, column) for PostgreSQL */
export function qi(identifier: string): string {
    // Doubling the quotes is the only escaping PostgreSQL needs inside "...".
    return `"${identifier.replace(/"/g, '""')}"`;
}

/**
 * @returns the PostgreSQL type of a field.
 * @throws if the type cannot be derived and no sqlType was declared.
 */
export function getFieldSqlType(model: EntitiesModel<any, any>, table: string, field: string): string {
    // Checked before asking the model: reading the type of a field that does not
    // exist gets a bare "Cannot read properties of undefined" out of it, which
    // says nothing about where the mistake is.
    if (!model.getTableFieldNames(table).map(String).includes(field)) {
        throw new Error(`Table "${table}", field "${field}": the field is not declared in the model`);
    }
    const typeName = model.getFieldTypeName(table, field);
    const definition = model.getTypeDefinition(typeName);
    if (definition == null) {
        throw new Error(`Table "${table}", field "${field}": type "${String(typeName)}" is not declared in the model`);
    }

    // An explicit declaration always wins: the model knows the JS type, the
    // developer knows how he wants it stored.
    if (definition.sqlType != null) {
        return definition.sqlType;
    }

    // The identity is generated by the database.
    if (model.isFieldIdentity(table, field)) {
        if (definition.rawType !== JSTypes.number) {
            throw new Error(`Table "${table}", field "${field}": an identity must be a number, got "${definition.rawType}"`);
        }
        return "SERIAL";
    }

    // A foreign key stores what SERIAL produces, which is an integer — true
    // whether it points at another table of the model or at system_users.
    if (model.isFieldForeign(table, field) || model.getFieldReferencesUsers(table, field)) {
        return "INTEGER";
    }

    const enumeration: EnumDefinition<any> | null = model.getEnum(typeName);
    if (enumeration != null) {
        // The values are the developer's own, and small by nature.
        return enumeration.rawType === JSTypes.string ? "TEXT" : "INTEGER";
    }

    switch (definition.rawType) {
        case JSTypes.boolean:
            return "BOOLEAN";
        case JSTypes.string:
            return "TEXT";
        case JSTypes.number:
            // Not INTEGER: a JS number *is* a double, so DOUBLE PRECISION is the
            // only mapping that never loses a value the application could hold.
            // Declare sqlType to narrow it.
            return "DOUBLE PRECISION";
        case JSTypes.object:
            return "JSONB";
        case JSTypes.custom:
            throw new Error(
                `Table "${table}", field "${field}": a "custom" type says nothing about storage, ` +
                `declare sqlType on the type "${String(typeName)}"`
            );
        default:
            throw new Error(`Table "${table}", field "${field}": unsupported raw type "${definition.rawType}"`);
    }
}

/** @returns the CREATE TABLE statement of a table of the model */
export function getCreateTableStatement<Model extends EntitiesModel<any, any>>(
    model: Model,
    table: string,
    options?: { ifNotExists?: boolean }
): string {
    const columns: string[] = [];

    for (const field of model.getTableFieldNames(table)) {
        const name = String(field);
        const parts: string[] = [qi(name), getFieldSqlType(model, table, name)];

        if (model.isFieldIdentity(table, name)) {
            parts.push("PRIMARY KEY");
        } else {
            if (!model.isFieldOptional(table, name)) {
                parts.push("NOT NULL");
            }
            const foreignTable = model.getFieldForeignTableName(table, name);
            if (foreignTable != null) {
                parts.push(`REFERENCES ${qi(model.getTableSqlName(foreignTable))}(${qi("id")})`);
            } else if (model.getFieldReferencesUsers(table, name)) {
                // ON DELETE SET NULL, like system_users.roleId -> system_roles.id:
                // a deleted account must not leave an orphaned or broken row, it
                // should just make the reference lose its attribution.
                parts.push(`REFERENCES ${qi(USERS_TABLE)}(${qi("id")}) ON DELETE SET NULL`);
            }
        }
        columns.push(parts.join(" "));
    }

    const exists = options?.ifNotExists ? "IF NOT EXISTS " : "";
    return `CREATE TABLE ${exists}${qi(model.getTableSqlName(table))} (\n    ${columns.join(",\n    ")}\n)`;
}

/**
 * @returns the tables of the model, ordered so a table always comes after the
 * ones it references. Creating them in declaration order would fail on the
 * first forward reference.
 * @throws on a cycle, which PostgreSQL could handle but the model cannot express.
 */
export function getTableCreationOrder(model: EntitiesModel<any, any>): string[] {
    const ordered: string[] = [];
    const visiting = new Set<string>();

    const visit = (table: string, path: string[]): void => {
        if (ordered.includes(table)) {
            return;
        }
        if (visiting.has(table)) {
            throw new Error(`Cycle between the foreign keys of the model: ${[...path, table].join(" -> ")}`);
        }
        visiting.add(table);
        for (const field of model.getTableFieldNames(table)) {
            const target = model.getFieldForeignTableName(table, String(field));
            // A self reference is fine: the table exists by the time the row does.
            if (target != null && target !== table) {
                visit(String(target), [...path, table]);
            }
        }
        visiting.delete(table);
        ordered.push(table);
    };

    for (const table of model.getTableNames()) {
        visit(String(table), []);
    }
    return ordered;
}
